# Generated by Django 3.1.5 on 2021-04-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0005_auto_20210310_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='service',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='timestamps',
            field=models.TextField(default='None'),
        ),
    ]
